steps:
  - id: test-builds-successfully
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    dir: $_DIR
    script: |
      gcloud builds submit 
serviceAccount: "gcp-lab-436609@appspot.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY
